// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nj4x.proto

#ifndef PROTOBUF_nj4x_2eproto__INCLUDED
#define PROTOBUF_nj4x_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_nj4x_2eproto();
void protobuf_AssignDesc_nj4x_2eproto();
void protobuf_ShutdownFile_nj4x_2eproto();

class Uni;

// ===================================================================

class Uni : public ::google::protobuf::MessageLite {
 public:
  Uni();
  virtual ~Uni();

  Uni(const Uni& from);

  inline Uni& operator=(const Uni& from) {
    CopyFrom(from);
    return *this;
  }

  static const Uni& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const Uni* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(Uni* other);

  // implements Message ----------------------------------------------

  Uni* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const Uni& from);
  void MergeFrom(const Uni& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 id = 10;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 10;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // optional int64 commandNo = 11;
  inline bool has_commandno() const;
  inline void clear_commandno();
  static const int kCommandNoFieldNumber = 11;
  inline ::google::protobuf::int64 commandno() const;
  inline void set_commandno(::google::protobuf::int64 value);

  // repeated int32 map = 1 [packed = true];
  inline int map_size() const;
  inline void clear_map();
  static const int kMapFieldNumber = 1;
  inline ::google::protobuf::int32 map(int index) const;
  inline void set_map(int index, ::google::protobuf::int32 value);
  inline void add_map(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      map() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_map();

  // repeated int32 intArgs = 2 [packed = true];
  inline int intargs_size() const;
  inline void clear_intargs();
  static const int kIntArgsFieldNumber = 2;
  inline ::google::protobuf::int32 intargs(int index) const;
  inline void set_intargs(int index, ::google::protobuf::int32 value);
  inline void add_intargs(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      intargs() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_intargs();

  // repeated int64 longArgs = 3 [packed = true];
  inline int longargs_size() const;
  inline void clear_longargs();
  static const int kLongArgsFieldNumber = 3;
  inline ::google::protobuf::int64 longargs(int index) const;
  inline void set_longargs(int index, ::google::protobuf::int64 value);
  inline void add_longargs(::google::protobuf::int64 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      longargs() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_longargs();

  // repeated double doubleArgs = 4 [packed = true];
  inline int doubleargs_size() const;
  inline void clear_doubleargs();
  static const int kDoubleArgsFieldNumber = 4;
  inline double doubleargs(int index) const;
  inline void set_doubleargs(int index, double value);
  inline void add_doubleargs(double value);
  inline const ::google::protobuf::RepeatedField< double >&
      doubleargs() const;
  inline ::google::protobuf::RepeatedField< double >*
      mutable_doubleargs();

  // repeated string strArgs = 5;
  inline int strargs_size() const;
  inline void clear_strargs();
  static const int kStrArgsFieldNumber = 5;
  inline const ::std::string& strargs(int index) const;
  inline ::std::string* mutable_strargs(int index);
  inline void set_strargs(int index, const ::std::string& value);
  inline void set_strargs(int index, const char* value);
  inline void set_strargs(int index, const char* value, size_t size);
  inline ::std::string* add_strargs();
  inline void add_strargs(const ::std::string& value);
  inline void add_strargs(const char* value);
  inline void add_strargs(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& strargs() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_strargs();

  // repeated bool boolArgs = 6 [packed = true];
  inline int boolargs_size() const;
  inline void clear_boolargs();
  static const int kBoolArgsFieldNumber = 6;
  inline bool boolargs(int index) const;
  inline void set_boolargs(int index, bool value);
  inline void add_boolargs(bool value);
  inline const ::google::protobuf::RepeatedField< bool >&
      boolargs() const;
  inline ::google::protobuf::RepeatedField< bool >*
      mutable_boolargs();

  // @@protoc_insertion_point(class_scope:Uni)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_commandno();
  inline void clear_has_commandno();

  ::google::protobuf::int64 commandno_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > map_;
  mutable int _map_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > intargs_;
  mutable int _intargs_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > longargs_;
  mutable int _longargs_cached_byte_size_;
  ::google::protobuf::RepeatedField< double > doubleargs_;
  mutable int _doubleargs_cached_byte_size_;
  ::google::protobuf::RepeatedPtrField< ::std::string> strargs_;
  ::google::protobuf::RepeatedField< bool > boolargs_;
  mutable int _boolargs_cached_byte_size_;
  ::google::protobuf::int32 id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(8 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_nj4x_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_nj4x_2eproto();
  #endif
  friend void protobuf_AssignDesc_nj4x_2eproto();
  friend void protobuf_ShutdownFile_nj4x_2eproto();

  void InitAsDefaultInstance();
  static Uni* default_instance_;
};
// ===================================================================


// ===================================================================

// Uni

// optional int32 id = 10;
inline bool Uni::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Uni::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Uni::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Uni::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 Uni::id() const {
  return id_;
}
inline void Uni::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// optional int64 commandNo = 11;
inline bool Uni::has_commandno() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Uni::set_has_commandno() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Uni::clear_has_commandno() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Uni::clear_commandno() {
  commandno_ = GOOGLE_LONGLONG(0);
  clear_has_commandno();
}
inline ::google::protobuf::int64 Uni::commandno() const {
  return commandno_;
}
inline void Uni::set_commandno(::google::protobuf::int64 value) {
  set_has_commandno();
  commandno_ = value;
}

// repeated int32 map = 1 [packed = true];
inline int Uni::map_size() const {
  return map_.size();
}
inline void Uni::clear_map() {
  map_.Clear();
}
inline ::google::protobuf::int32 Uni::map(int index) const {
  return map_.Get(index);
}
inline void Uni::set_map(int index, ::google::protobuf::int32 value) {
  map_.Set(index, value);
}
inline void Uni::add_map(::google::protobuf::int32 value) {
  map_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
Uni::map() const {
  return map_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
Uni::mutable_map() {
  return &map_;
}

// repeated int32 intArgs = 2 [packed = true];
inline int Uni::intargs_size() const {
  return intargs_.size();
}
inline void Uni::clear_intargs() {
  intargs_.Clear();
}
inline ::google::protobuf::int32 Uni::intargs(int index) const {
  return intargs_.Get(index);
}
inline void Uni::set_intargs(int index, ::google::protobuf::int32 value) {
  intargs_.Set(index, value);
}
inline void Uni::add_intargs(::google::protobuf::int32 value) {
  intargs_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
Uni::intargs() const {
  return intargs_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
Uni::mutable_intargs() {
  return &intargs_;
}

// repeated int64 longArgs = 3 [packed = true];
inline int Uni::longargs_size() const {
  return longargs_.size();
}
inline void Uni::clear_longargs() {
  longargs_.Clear();
}
inline ::google::protobuf::int64 Uni::longargs(int index) const {
  return longargs_.Get(index);
}
inline void Uni::set_longargs(int index, ::google::protobuf::int64 value) {
  longargs_.Set(index, value);
}
inline void Uni::add_longargs(::google::protobuf::int64 value) {
  longargs_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
Uni::longargs() const {
  return longargs_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
Uni::mutable_longargs() {
  return &longargs_;
}

// repeated double doubleArgs = 4 [packed = true];
inline int Uni::doubleargs_size() const {
  return doubleargs_.size();
}
inline void Uni::clear_doubleargs() {
  doubleargs_.Clear();
}
inline double Uni::doubleargs(int index) const {
  return doubleargs_.Get(index);
}
inline void Uni::set_doubleargs(int index, double value) {
  doubleargs_.Set(index, value);
}
inline void Uni::add_doubleargs(double value) {
  doubleargs_.Add(value);
}
inline const ::google::protobuf::RepeatedField< double >&
Uni::doubleargs() const {
  return doubleargs_;
}
inline ::google::protobuf::RepeatedField< double >*
Uni::mutable_doubleargs() {
  return &doubleargs_;
}

// repeated string strArgs = 5;
inline int Uni::strargs_size() const {
  return strargs_.size();
}
inline void Uni::clear_strargs() {
  strargs_.Clear();
}
inline const ::std::string& Uni::strargs(int index) const {
  return strargs_.Get(index);
}
inline ::std::string* Uni::mutable_strargs(int index) {
  return strargs_.Mutable(index);
}
inline void Uni::set_strargs(int index, const ::std::string& value) {
  strargs_.Mutable(index)->assign(value);
}
inline void Uni::set_strargs(int index, const char* value) {
  strargs_.Mutable(index)->assign(value);
}
inline void Uni::set_strargs(int index, const char* value, size_t size) {
  strargs_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Uni::add_strargs() {
  return strargs_.Add();
}
inline void Uni::add_strargs(const ::std::string& value) {
  strargs_.Add()->assign(value);
}
inline void Uni::add_strargs(const char* value) {
  strargs_.Add()->assign(value);
}
inline void Uni::add_strargs(const char* value, size_t size) {
  strargs_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
Uni::strargs() const {
  return strargs_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
Uni::mutable_strargs() {
  return &strargs_;
}

// repeated bool boolArgs = 6 [packed = true];
inline int Uni::boolargs_size() const {
  return boolargs_.size();
}
inline void Uni::clear_boolargs() {
  boolargs_.Clear();
}
inline bool Uni::boolargs(int index) const {
  return boolargs_.Get(index);
}
inline void Uni::set_boolargs(int index, bool value) {
  boolargs_.Set(index, value);
}
inline void Uni::add_boolargs(bool value) {
  boolargs_.Add(value);
}
inline const ::google::protobuf::RepeatedField< bool >&
Uni::boolargs() const {
  return boolargs_;
}
inline ::google::protobuf::RepeatedField< bool >*
Uni::mutable_boolargs() {
  return &boolargs_;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_nj4x_2eproto__INCLUDED
