
package com.jfx.net.tsapi;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ExpertDoesNotExistsException", targetNamespace = "http://experts.nj4x.com/")
public class ExpertDoesNotExistsException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ExpertDoesNotExistsException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ExpertDoesNotExistsException_Exception(String message, ExpertDoesNotExistsException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ExpertDoesNotExistsException_Exception(String message, ExpertDoesNotExistsException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.jfx.net.tsapi.ExpertDoesNotExistsException
     */
    public ExpertDoesNotExistsException getFaultInfo() {
        return faultInfo;
    }

}
