
package com.jfx.net.tsapi;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "Nj4xSessionExpiredException", targetNamespace = "http://ts.nj4x.com/")
public class Nj4XSessionExpiredException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private Nj4XSessionExpiredException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public Nj4XSessionExpiredException_Exception(String message, Nj4XSessionExpiredException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public Nj4XSessionExpiredException_Exception(String message, Nj4XSessionExpiredException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.jfx.net.tsapi.Nj4XSessionExpiredException
     */
    public Nj4XSessionExpiredException getFaultInfo() {
        return faultInfo;
    }

}
