
package com.jfx.net.tsapi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TesterService", targetNamespace = "http://tester.nj4x.com/", wsdlLocation = "file:/C:/projects/nj4x-api/nj4x-ts/target/generated-sources/wsdl/TesterWS.wsdl")
public class TesterService
    extends Service
{

    private final static URL TESTERSERVICE_WSDL_LOCATION;
    private final static WebServiceException TESTERSERVICE_EXCEPTION;
    private final static QName TESTERSERVICE_QNAME = new QName("http://tester.nj4x.com/", "TesterService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/projects/nj4x-api/nj4x-ts/target/generated-sources/wsdl/TesterWS.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TESTERSERVICE_WSDL_LOCATION = url;
        TESTERSERVICE_EXCEPTION = e;
    }

    public TesterService() {
        super(__getWsdlLocation(), TESTERSERVICE_QNAME);
    }

    public TesterService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TESTERSERVICE_QNAME, features);
    }

    public TesterService(URL wsdlLocation) {
        super(wsdlLocation, TESTERSERVICE_QNAME);
    }

    public TesterService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TESTERSERVICE_QNAME, features);
    }

    public TesterService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TesterService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Tester
     */
    @WebEndpoint(name = "TesterPort")
    public Tester getTesterPort() {
        return super.getPort(new QName("http://tester.nj4x.com/", "TesterPort"), Tester.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Tester
     */
    @WebEndpoint(name = "TesterPort")
    public Tester getTesterPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://tester.nj4x.com/", "TesterPort"), Tester.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TESTERSERVICE_EXCEPTION!= null) {
            throw TESTERSERVICE_EXCEPTION;
        }
        return TESTERSERVICE_WSDL_LOCATION;
    }

}
