
package com.jfx.net.tsapi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Tester", targetNamespace = "http://tester.nj4x.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Tester {


    /**
     * 
     * @param mt4Account
     * @param expertParams
     * @param token
     * @return
     *     returns java.lang.String
     * @throws Nj4XInvalidTokenException_Exception
     * @throws Nj4XSessionExpiredException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "runMT4Expert", targetNamespace = "http://tester.nj4x.com/", className = "com.jfx.net.tsapi.RunMT4Expert")
    @ResponseWrapper(localName = "runMT4ExpertResponse", targetNamespace = "http://tester.nj4x.com/", className = "com.jfx.net.tsapi.RunMT4ExpertResponse")
    public String runMT4Expert(
        @WebParam(name = "token", targetNamespace = "")
        long token,
        @WebParam(name = "mt4Account", targetNamespace = "")
        Nj4XMT4Account mt4Account,
        @WebParam(name = "expertParams", targetNamespace = "")
        Mt4ExpertParams expertParams)
        throws Nj4XInvalidTokenException_Exception, Nj4XSessionExpiredException_Exception
    ;

    /**
     * 
     * @param mt4Account
     * @param expertParams
     * @param token
     * @return
     *     returns java.lang.String
     * @throws Nj4XInvalidTokenException_Exception
     * @throws Nj4XSessionExpiredException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "killMT4Expert", targetNamespace = "http://tester.nj4x.com/", className = "com.jfx.net.tsapi.KillMT4Expert")
    @ResponseWrapper(localName = "killMT4ExpertResponse", targetNamespace = "http://tester.nj4x.com/", className = "com.jfx.net.tsapi.KillMT4ExpertResponse")
    public String killMT4Expert(
        @WebParam(name = "token", targetNamespace = "")
        long token,
        @WebParam(name = "mt4Account", targetNamespace = "")
        Nj4XMT4Account mt4Account,
        @WebParam(name = "expertParams", targetNamespace = "")
        Mt4ExpertParams expertParams)
        throws Nj4XInvalidTokenException_Exception, Nj4XSessionExpiredException_Exception
    ;

    /**
     * 
     * @param mt4Account
     * @param expertTesterParams
     * @param token
     * @return
     *     returns com.jfx.net.tsapi.Mt4TesterReport
     * @throws Nj4XInvalidTokenException_Exception
     * @throws Nj4XSessionExpiredException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "runMT4Tester", targetNamespace = "http://tester.nj4x.com/", className = "com.jfx.net.tsapi.RunMT4Tester")
    @ResponseWrapper(localName = "runMT4TesterResponse", targetNamespace = "http://tester.nj4x.com/", className = "com.jfx.net.tsapi.RunMT4TesterResponse")
    public Mt4TesterReport runMT4Tester(
        @WebParam(name = "token", targetNamespace = "")
        long token,
        @WebParam(name = "mt4Account", targetNamespace = "")
        Nj4XMT4Account mt4Account,
        @WebParam(name = "expertTesterParams", targetNamespace = "")
        Mt4ExpertTesterParams expertTesterParams)
        throws Nj4XInvalidTokenException_Exception, Nj4XSessionExpiredException_Exception
    ;

    /**
     * 
     * @param clientInfo
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "startSession", targetNamespace = "http://tester.nj4x.com/", className = "com.jfx.net.tsapi.StartSession")
    @ResponseWrapper(localName = "startSessionResponse", targetNamespace = "http://tester.nj4x.com/", className = "com.jfx.net.tsapi.StartSessionResponse")
    public long startSession(
        @WebParam(name = "clientInfo", targetNamespace = "")
        Nj4XClientInfo clientInfo);

    /**
     * 
     * @param token
     * @return
     *     returns com.jfx.net.tsapi.Nj4XTSInfo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTSInfo", targetNamespace = "http://tester.nj4x.com/", className = "com.jfx.net.tsapi.GetTSInfo")
    @ResponseWrapper(localName = "getTSInfoResponse", targetNamespace = "http://tester.nj4x.com/", className = "com.jfx.net.tsapi.GetTSInfoResponse")
    public Nj4XTSInfo getTSInfo(
        @WebParam(name = "token", targetNamespace = "")
        long token);

    /**
     * 
     * @param token
     */
    @WebMethod
    @RequestWrapper(localName = "close", targetNamespace = "http://tester.nj4x.com/", className = "com.jfx.net.tsapi.Close")
    @ResponseWrapper(localName = "closeResponse", targetNamespace = "http://tester.nj4x.com/", className = "com.jfx.net.tsapi.CloseResponse")
    public void close(
        @WebParam(name = "token", targetNamespace = "")
        long token);

}
