
package com.jfx.net.tsapi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TSService", targetNamespace = "http://ts.nj4x.com/", wsdlLocation = "file:/C:/projects/nj4x-api/nj4x-ts/target/generated-sources/wsdl/TsWS.wsdl")
public class TSService
    extends Service
{

    private final static URL TSSERVICE_WSDL_LOCATION;
    private final static WebServiceException TSSERVICE_EXCEPTION;
    private final static QName TSSERVICE_QNAME = new QName("http://ts.nj4x.com/", "TSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/projects/nj4x-api/nj4x-ts/target/generated-sources/wsdl/TsWS.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TSSERVICE_WSDL_LOCATION = url;
        TSSERVICE_EXCEPTION = e;
    }

    public TSService() {
        super(__getWsdlLocation(), TSSERVICE_QNAME);
    }

    public TSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TSSERVICE_QNAME, features);
    }

    public TSService(URL wsdlLocation) {
        super(wsdlLocation, TSSERVICE_QNAME);
    }

    public TSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TSSERVICE_QNAME, features);
    }

    public TSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TS
     */
    @WebEndpoint(name = "TSPort")
    public TS getTSPort() {
        return super.getPort(new QName("http://ts.nj4x.com/", "TSPort"), TS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TS
     */
    @WebEndpoint(name = "TSPort")
    public TS getTSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ts.nj4x.com/", "TSPort"), TS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TSSERVICE_EXCEPTION!= null) {
            throw TSSERVICE_EXCEPTION;
        }
        return TSSERVICE_WSDL_LOCATION;
    }

}
