/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jfx_ts_io_BoxUtils */

#ifndef _Included_com_jfx_ts_io_BoxUtils
#define _Included_com_jfx_ts_io_BoxUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jfx_ts_io_BoxUtils
 * Method:    boxid
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_jfx_ts_io_BoxUtils_boxid
  (JNIEnv *, jclass);

/*
 * Class:     com_jfx_ts_io_BoxUtils
 * Method:    getBinaryType
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_jfx_ts_io_BoxUtils_getBinaryType
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
